import click
import json
from sklearn.model_selection import ParameterGrid
from ivbase.utils.constants.alphabet import SMILES_ALPHABET

dataset_params = list(ParameterGrid(
    dict(dataset_name=["twosides"],
         transformer=["seq"],
         split_mode=["random"],
         test_size=[0.15],
         valid_size=[0.10],
         seed=[42],
         decagon=[False],
         use_side_effects_mapping=[True],
         use_as_filter=[['thrombocytopenia'],
                        ['bilirubinaemia'],
                        ['bacterial infection'],
                        ['haematochezia'],
                        ['hepatic failure'],
                        ['icterus'],
                        ['body temperature increased'],
                        ['sepsis'],
                        ['abnormal lfts'],
                        ['fungal disease'],
                        ['pancreatitis'],
                        ['arterial pressure nos decreased'],
                        ['difficulty breathing'],
                        ['anaemia'],
                        ['heart rate increased'],
                        ['road traffic accident'],
                        ['afib'],
                        ['sinus tachycardia'],
                        ['anaphylactic reaction'],
                        ['dizziness'],
                        ['arteriosclerotic heart disease'],
                        ['heart attack'],
                        ['angina'],
                        ['femur fracture'],
                        ['cough'],
                        ['cervical vertebral fracture'],
                        ['aspiration pneumonia'],
                        ['anxiety'],
                        ['tinnitus'],
                        ['edema'],
                        ['infection viral'],
                        ['cardiac decompensation'],
                        ['lung infiltration'],
                        ['cardiac enlargement'],
                        ['insomnia'],
                        ['bleeding hemorrhoids'],
                        ['extrasystoles ventricular'],
                        ['drug hypersensitivity'],
                        ['pleural pain'],
                        ['embolism pulmonary'],
                        ['erosive gastritis'],
                        ['neuropathy'],
                        ['dyspepsia'],
                        ['extremity pain'],
                        ['colitis'],
                        ['orthopnea'],
                        ['hypoventilation'],
                        ['dehydration'],
                        ['difficulty in walking'],
                        ['high blood pressure'],
                        ['spondylosis'],
                        ['hyperlipaemia'],
                        ['cardiomyopathy'],
                        ['pleurisy'],
                        ['burning sensation'],
                        ['drowsiness'],
                        ['bundle branch block left'],
                        ['diarrhea'],
                        ['chest pain'],
                        ['fatigue'],
                        ['proctalgia'],
                        ['nausea'],
                        ['neumonia'],
                        ['head ache'],
                        ['elevated cholesterol'],
                        ['palpitation'],
                        ['haemorrhoids'],
                        ['nightmare'],
                        ['anorexia'],
                        ['still birth'],
                        ['enlarged spleen'],
                        ['enlarged liver'],
                        ['pericarditis'],
                        ['loss of weight'],
                        ['ventricular fibrillation'],
                        ['aphasia'],
                        ['hyperhidrosis'],
                        ['cholelithiasis'],
                        ['hip fracture'],
                        ['gastrointestinal bleed'],
                        ['infection'],
                        ['muscle weakness'],
                        ['blepharospasm'],
                        ['blurred vision'],
                        ['infection urinary tract'],
                        ['intervertebral disc disorder'],
                        ['fractured pelvis nos'],
                        ['polymyositis'],
                        ['psychoses'],
                        ['neuralgia'],
                        ['feeling unwell'],
                        ['narcolepsy'],
                        ['agitated'],
                        ['joint swelling'],
                        ['drug toxicity nos'],
                        ['emesis'],
                        ['neoplasia'],
                        ['polyp'],
                        ['pyelonephritis'],
                        ['erythema'],
                        ['facial flushing'],
                        ['folate deficiency'],
                        ['asystole'],
                        ['dental caries'],
                        ['kidney failure'],
                        ['tendinitis'],
                        ['acute kidney failure'],
                        ['hepatitis'],
                        ['weight gain'],
                        ['abdominal pain'],
                        ['food intolerance'],
                        ['rhabdomyolysis'],
                        ['cryptococcosis'],
                        ['gall bladder'],
                        ['bradycardia'],
                        ['convulsion'],
                        ['deglutition disorder'],
                        ['confusion'],
                        ['encephalopathy'],
                        ['septic shock'],
                        ['cardiac valvulopathy'],
                        ['arterial pressure nos increased'],
                        ['aching muscles'],
                        ['failure to thrive'],
                        ['cachectic'],
                        ['convulsions grand mal'],
                        ['abnormal eeg'],
                        ['cardiac failure'],
                        ['pulmonary arrest'],
                        ['hallucination'],
                        ['hyperglycaemia'],
                        ['abdominal hernia'],
                        ['sinus arrest'],
                        ['atrioventricular block'],
                        ['apoplexy'],
                        ['pyoderma'],
                        ['blood calcium increased'],
                        ['asthenia'],
                        ['aplasia pure red cell'],
                        ['pain'],
                        ['benign intracranial hypertension'],
                        ['amenorrhea'],
                        ['sensory disturbance'],
                        ['skin striae'],
                        ['muscle paresis'],
                        ['muscle disorder'],
                        ['fainting'],
                        ['bladder cancer'],
                        ['bleeding vaginal'],
                        ['uterine bleeding'],
                        ['drug withdrawal'],
                        ['muscle spasm'],
                        ['bladder retention'],
                        ['neuropathy peripheral'],
                        ['metabolic acidosis'],
                        ['pericardial effusion'],
                        ['sinusitis'],
                        ['bone pain'],
                        ['haemorrhage rectum'],
                        ['angiopathy'],
                        ['breast disorder'],
                        ['hernia hiatal'],
                        ['leucocytosis'],
                        ['haematoma'],
                        ['intestinal perforation'],
                        ['alopecia'],
                        ['aptyalism'],
                        ['ischaemia'],
                        ['hypercapnia'],
                        ['epilepsy'],
                        ['allergic dermatitis'],
                        ['neutropenia'],
                        ['paraesthesia'],
                        ['edema extremities'],
                        ['loss of consciousness'],
                        ['movement disorder'],
                        ['decreased body temperature'],
                        ['abdominal distension'],
                        ['fibromyalgia'],
                        ['disorder renal'],
                        ['nocturia'],
                        ['hypotension orthostatic'],
                        ['cataract'],
                        ['aseptic necrosis bone'],
                        ['ild'],
                        ['nephrolithiasis'],
                        ['blindness'],
                        ['optic atrophy'],
                        ['bronchitis'],
                        ['arthritis'],
                        ['excess potassium'],
                        ['aseptic meningitis'],
                        ['ovarian cyst'],
                        ['leucopenia'],
                        ['lung neoplasms'],
                        ['pleural effusion'],
                        ['agranulocytoses'],
                        ['ebv infection'],
                        ['apnea'],
                        ['aspergillosis'],
                        ['bone marrow failure'],
                        ['aspartate aminotransferase increase'],
                        ['epistaxis'],
                        ['decubitus ulcer'],
                        ['conjunctivitis'],
                        ['peliosis'],
                        ['coughing blood'],
                        ['respiratory failure'],
                        ['mouth bleeding'],
                        ['pneumothorax'],
                        ['right heart failure'],
                        ['ascites'],
                        ['hypoglycaemia'],
                        ['black stools'],
                        ['incontinence'],
                        ['hydrocephalus'],
                        ['cmv infection'],
                        ['bacteraemia'],
                        ['itch'],
                        ['disorder lung'],
                        ['abnormal gait'],
                        ['chill'],
                        ['nephrosclerosis'],
                        ['eruption'],
                        ['hypoxia'],
                        ['excoriation'],
                        ['tremor'],
                        ['lyell'],
                        ['left ventricular hypertrophy'],
                        ['cognitive disorder'],
                        ['hemiplegia'],
                        ['bleeding'],
                        ['cerebral infarct'],
                        ['acidosis'],
                        ['pneumocystis carinii pneumonia'],
                        ['pulmonary hypertension'],
                        ['adenopathy'],
                        ['atelectasis'],
                        ['ureteral obstruction'],
                        ['herpes zoster'],
                        ['raynauds phenomenon'],
                        ['multifocal leukoencephalopathy'],
                        ['allergies'],
                        ['hematoma subdural'],
                        ['acute respiratory distress syndrome'],
                        ['angiitis'],
                        ['alcoholic intoxication'],
                        ['ekbom syndrome'],
                        ['stridor'],
                        ['viral pharyngitis'],
                        ['acute bronchitis'],
                        ['birth defect'],
                        ['decreased hearing'],
                        ['bronchiolitis'],
                        ['bulging'],
                        ['caesarean section'],
                        ['idiopathic thrombocytopenic purpura'],
                        ['dysphasia'],
                        ['chicken pox'],
                        ['deafness neurosensory'],
                        ['cheilosis'],
                        ['infection upper respiratory'],
                        ['anemia aplastic'],
                        ['mucositis oral'],
                        ['excessive thirst'],
                        ['enterocolitis'],
                        ['lung edema'],
                        ['herpes simplex'],
                        ['cardiac ischemia'],
                        ['wheeze'],
                        ['gouty arthritis'],
                        ['constipated'],
                        ['glossitis'],
                        ['light sensitivity'],
                        ['increased white blood cell count'],
                        ['bacterial vaginitis'],
                        ['deep vein thromboses'],
                        ['elevated erythrocyte sedimentation rate'],
                        ['increased platelet count'],
                        ['detached retina'],
                        ['polyuria'],
                        ['bone marrow transplant'],
                        ['bacterial pneumonia'],
                        ['cardiovascular collapse'],
                        ['gastric inflammation'],
                        ['nasopharyngitis'],
                        ['hypokalaemia'],
                        ['chronic kidney disease'],
                        ['portal hypertension'],
                        ['disease of liver'],
                        ['haemolytic anaemia'],
                        ['hypogammaglobulinaemia'],
                        ['cerebral ischaemia'],
                        ['coma'],
                        ['blood calcium decreased'],
                        ['anisocoria'],
                        ['atrial ectopic beats'],
                        ['cardiac murmur'],
                        ['dysphonia'],
                        ['adenitis'],
                        ['mouth ulcer'],
                        ['abscess'],
                        ['candida infection'],
                        ['status epilepticus'],
                        ['hepatic encephalopathy'],
                        ['autonomic instability'],
                        ['glucose intolerance'],
                        ['blood in urine'],
                        ['blood sodium decreased'],
                        ['acne'],
                        ['migraine'],
                        ['hemiparesis'],
                        ['dental pain'],
                        ['dental abscess'],
                        ['abdominal pain upper'],
                        ['nasal sinus congestion'],
                        ['aching joints'],
                        ['colitis pseudomembranous'],
                        ['arrhythmia'],
                        ['face pain'],
                        ['osteoporosis'],
                        ['arthritis rheumatoid'],
                        ['hyperparathyroidism'],
                        ['osteoarthritis'],
                        ['angioedema'],
                        ['basal cell carcinoma'],
                        ['myelodysplasia'],
                        ['hydronephrosis'],
                        ['nasal congestion'],
                        ['back ache'],
                        ['haematemesis'],
                        ['odynophagia'],
                        ['cerebral atrophy'],
                        ['sinus bradycardia'],
                        ['nodule skin'],
                        ['phlebothrombosis'],
                        ['rhinitis'],
                        ['tachycardia ventricular'],
                        ['cervicalgia'],
                        ['spinning sensation'],
                        ['nystagmus'],
                        ['peritonitis'],
                        ['glucosuria'],
                        ['palsies'],
                        ['cholecystitis'],
                        ['elevated triglycerides'],
                        ['malabsorption'],
                        ['mod'],
                        ['optic disc edema'],
                        ['candidiasis of mouth'],
                        ['ear infection'],
                        ['abnormal movements'],
                        ['erythema multiforme'],
                        ['diplopia'],
                        ['fib'],
                        ['soft tissue infection'],
                        ['gastric ulcer'],
                        ['mouth pain'],
                        ['petit mal'],
                        ['platelet disorder'],
                        ['pneumonia klebsiella'],
                        ['abnormal laboratory findings'],
                        ['lower gi bleeding'],
                        ['strabismus'],
                        ['viral pneumonia'],
                        ['bundle branch block right'],
                        ['retinal bleeding'],
                        ['cardiac disease'],
                        ['embolism'],
                        ['transient ischaemic attack'],
                        ['hyperuricaemia'],
                        ['acid reflux'],
                        ['bladder inflammation'],
                        ['pain in throat'],
                        ['bundle branch block'],
                        ['diverticulitis'],
                        ['intestinal ulcer'],
                        ['enuresis'],
                        ['muscle inflammation'],
                        ['bronchial spasm'],
                        ['neonatal respiratory distress syndrome'],
                        ['electrolyte disorder'],
                        ['hiccough'],
                        ['excessive salivation'],
                        ['hepatic necrosis'],
                        ['petechia'],
                        ['dysarthria'],
                        ['pharyngeal inflammation'],
                        ['cutaneous candidiasis'],
                        ['esophagitis'],
                        ['fatty liver'],
                        ['arthropathy'],
                        ['cerebral haemorrhage'],
                        ['head injury'],
                        ['adenocarcinoma'],
                        ['hypernatraemia'],
                        ['portal vein thrombosis'],
                        ['syncope vasovagal'],
                        ['diabetes'],
                        ['eosinophil count increased'],
                        ['acute brain syndrome'],
                        ['duodenal ulcer'],
                        ['malnourished'],
                        ['lymphocytes decreased'],
                        ['dry eye'],
                        ['goiter'],
                        ['proteinuria'],
                        ['hypophosphataemia'],
                        ['small intestinal obstruction'],
                        ['anosmia'],
                        ['cellulitis'],
                        ['candidiasis of vagina'],
                        ['vaginal discharge'],
                        ['antinuclear antibody positive'],
                        ['psoriasis'],
                        ['blood pressure abnormal'],
                        ['spinal fracture'],
                        ['gastroenteritis'],
                        ['ecchymoses'],
                        ['lobar pneumonia'],
                        ['hive'],
                        ['anal fistula'],
                        ['cholecystectomies'],
                        ['cyst'],
                        ['multiple sclerosis'],
                        ['adynamic ileus'],
                        ['phlebitis'],
                        ['eating disorder'],
                        ['ear ache'],
                        ['adrenal insufficiency'],
                        ['renal cyst'],
                        ['hypomagnesaemia'],
                        ['dyspnea exertional'],
                        ['malignant melanoma'],
                        ['carcinoma of the colon'],
                        ['polyarthritis'],
                        ['fistula'],
                        ['supraventricular tachycardia'],
                        ['cramp'],
                        ['lymphoma'],
                        ['breast cancer'],
                        ['thyroid neoplasia'],
                        ['colon spastic'],
                        ['colonic polyp'],
                        ['tracheitis'],
                        ['obstructive uropathy'],
                        ['gastroenteritis viral'],
                        ['hyperthyroidism'],
                        ['thyroid disease'],
                        ['arteriosclerosis'],
                        ['flu'],
                        ['hypochloraemia'],
                        ['enteritis'],
                        ['bruise'],
                        ['glossodynia'],
                        ['sneezing'],
                        ['aortic regurgitation'],
                        ['aortic stenosis'],
                        ['choking'],
                        ['eye pain'],
                        ['rotator cuff syndrome'],
                        ['vitamin b 12 deficiency'],
                        ['amnesia'],
                        ['dyspnoea paroxysmal nocturnal'],
                        ['haemorrhage intracranial'],
                        ['brain abscess'],
                        ['dermatitis medicamentosa'],
                        ['subarachnoid haemorrhage'],
                        ['bleb'],
                        ['lung fibrosis'],
                        ['clotting'],
                        ['multiple myeloma'],
                        ['cardiac tamponade'],
                        ['encephalitis'],
                        ['vitamin d deficiency'],
                        ['abnormal vision'],
                        ['ataxia'],
                        ['micturition urgency'],
                        ['obesity'],
                        ['acute pancreatitis'],
                        ['dermatitis exfoliative'],
                        ['cerebral vascular disorder'],
                        ['osteomalacia'],
                        ['eye swelling'],
                        ['cutaneous ulcer'],
                        ['pulmonary mass'],
                        ['lipoma'],
                        ['macula lutea degeneration'],
                        ['ulcer'],
                        ['upper gastrointestinal bleeding'],
                        ['gangrene'],
                        ['contact dermatitis'],
                        ['streptococcal infection'],
                        ['eosinophilic pneumonia'],
                        ['musculoskeletal pain'],
                        ['gastric cancer'],
                        ['carcinoma of the cervix'],
                        ['cancer'],
                        ['motor retardation'],
                        ['acute myeloblastic leukemia'],
                        ['hypothyroid'],
                        ['rib fracture'],
                        ['nail disorder'],
                        ['myocarditis'],
                        ['balance disorder'],
                        ['atrial flutter'],
                        ['pharyngitis streptococcal'],
                        ['laryngitis'],
                        ['joint effusion'],
                        ['disseminated lupus erythematosus'],
                        ['belching'],
                        ['liver abscess'],
                        ['hordeolum'],
                        ['dry skin'],
                        ['diabetic acidosis'],
                        ['sleep disorder'],
                        ['acute sinusitis'],
                        ['parkinson'],
                        ['myoglobinuria'],
                        ['esophageal stenosis'],
                        ['endocarditis'],
                        ['reflux esophagitis'],
                        ['esophageal ulcer'],
                        ['metabolic encephalopathy'],
                        ['duodenal ulcer perforation'],
                        ['amentia'],
                        ['flank pain'],
                        ['granuloma'],
                        ['hyperpigmentation'],
                        ['neuritis'],
                        ['gingivitis'],
                        ['floaters'],
                        ['lung neoplasm malignant'],
                        ['periodontal disease'],
                        ['gingival pain'],
                        ['ischias'],
                        ['abnormal ecg'],
                        ['bruxism'],
                        ['cholecystitis acute'],
                        ['spinal compression fracture'],
                        ['perirectal abscess'],
                        ['gastric polyps'],
                        ['esophageal cancer'],
                        ['rhinorrhea'],
                        ['anaemia hypochromic'],
                        ['gastroduodenal ulcer'],
                        ['nodule'],
                        ['superficial thrombophlebitis'],
                        ['fecal occult blood'],
                        ['tympanic membrane perforation'],
                        ['lung abscess'],
                        ['near syncope'],
                        ['external ear infection'],
                        ['pneumonia primary atypical'],
                        ['respiratory alkalosis'],
                        ['panic attack'],
                        ['paraparesis'],
                        ['sleep apnea'],
                        ['panic disorder'],
                        ['costochondritis'],
                        ['agoraphobia'],
                        ['altered bowel function'],
                        ['hoarseness'],
                        ['flatulence'],
                        ['decreased libido'],
                        ['skin lesion'],
                        ['urosepsis'],
                        ['bone fracture spontaneous'],
                        ['allergic vasculitis'],
                        ['actinic keratosis'],
                        ['dysuria'],
                        ['thrombotic microangiopathy'],
                        ['allergic alveolitis'],
                        ['lung adenocarcinoma'],
                        ['glaucoma'],
                        ['colitis ischemic'],
                        ['chronic obstructive airway disease'],
                        ['arachnoiditis'],
                        ['quadriplegia'],
                        ['polyneuropathy'],
                        ['folliculitis'],
                        ['cholangitis'],
                        ['ankle fracture'],
                        ['hepatitis toxic'],
                        ['biliary tract disorder'],
                        ['haemangioma'],
                        ['atherosclerosis'],
                        ['psoriatic arthritis'],
                        ['asthma'],
                        ['atrioventricular block second degree'],
                        ['calculus ureteric'],
                        ['hernia'],
                        ['hydroureter'],
                        ['meningioma'],
                        ['nervous tension'],
                        ['nephrotic syndrome'],
                        ['faecal incontinence'],
                        ['carcinoma of prostate'],
                        ['insulin dependent diabetes mellitus'],
                        ['superior vena cava syndrome'],
                        ['gout'],
                        ['fibrosing alveolitis'],
                        ['proctitis'],
                        ['retrocollis'],
                        ['eyelid diseases'],
                        ['atrioventricular block complete'],
                        ['atrioventricular block first degree'],
                        ['hot flash'],
                        ['chest infection'],
                        ['blepharoptosis'],
                        ['wound dehiscence'],
                        ['hernia inguinal'],
                        ['nephrocalcinosis'],
                        ['paronychia'],
                        ['pigmentation disorder'],
                        ['meningitis viral'],
                        ['bursitis'],
                        ['hepatitis b'],
                        ['bone spur'],
                        ['tooth disease'],
                        ['parotitis'],
                        ['choreoathetosis'],
                        ['diverticulosis'],
                        ['mediastinal disorder'],
                        ['seroma'],
                        ['swollen scrotum'],
                        ['dysaesthesia'],
                        ['hypovitaminosis'],
                        ['impetigo'],
                        ['defaecation urgency'],
                        ['bleeding gums'],
                        ['pyoderma gangrenosum'],
                        ['pleural fibrosis'],
                        ['parotid gland enlargement'],
                        ['personality disorder'],
                        ['acne rosacea'],
                        ['blood disorder'],
                        ['pancreatic pseudocyst'],
                        ['atrophy of skin'],
                        ['ketoacidosis'],
                        ['splenic infarction'],
                        ['myopia'],
                        ['malignant hypertension'],
                        ['epidural abscess'],
                        ['panniculitis'],
                        ['duodenitis'],
                        ['aortic aneurysm'],
                        ['iron deficiency anaemia'],
                        ['ear discharge'],
                        ['renal colic'],
                        ['azotaemia'],
                        ['aphthous stomatitis'],
                        ['cirrhosis'],
                        ['breakthrough bleeding'],
                        ['facial palsy'],
                        ['cerebral artery embolism'],
                        ['adh inappropriate'],
                        ['myasthenia gravis'],
                        ['keratitis sicca'],
                        ['duodenal ulcer haemorrhage'],
                        ['vitreous haemorrhage'],
                        ['hepatic neoplasia'],
                        ['apraxia'],
                        ['appendicitis'],
                        ['cold extremities'],
                        ['cutaneous mycosis'],
                        ['ovarian cancer'],
                        ['colonic obstruction'],
                        ['colpitis'],
                        ['hyperaesthesia'],
                        ['eustachian tube disorder'],
                        ['postmenopausal bleeding'],
                        ['chronic sinusitis'],
                        ['anal fissure'],
                        ['testes pain'],
                        ['shoulder pain'],
                        ['humerus fracture'],
                        ['arthritis infective'],
                        ['vitreous detachment'],
                        ['eye injury'],
                        ['dislocation'],
                        ['back injury'],
                        ['inflammatory bowel disease'],
                        ['gun shot wound'],
                        ['incisional hernia'],
                        ['sinus headache'],
                        ['varicose vein'],
                        ['wrist fracture'],
                        ['dermatitides'],
                        ['emphysema'],
                        ['abnormal mammogram'],
                        ['endocrine disorder'],
                        ['mycobacterium tuberculosis infection'],
                        ['kidney pain'],
                        ['abortion spontaneous'],
                        ['furuncle'],
                        ['osteomyelitis'],
                        ['premature menopause'],
                        ['pain pelvic'],
                        ['vocal cord paralysis'],
                        ['chronic ulcerative colitis'],
                        ['renal tubular acidosis'],
                        ['chronic hepatitis'],
                        ['labyrinthitis'],
                        ['epidural hematoma'],
                        ['ventricular septal defect'],
                        ['allergic rhinitis'],
                        ['irregular menstrual cycle'],
                        ['bradyarrhythmia'],
                        ['adenoma'],
                        ['scar'],
                        ['fibroids'],
                        ['joint stiffness'],
                        ['cor pulmonale'],
                        ['night sweat'],
                        ['eczema'],
                        ['connective tissue disease'],
                        ['breast lump'],
                        ['splenectomy'],
                        ['patent ductus arteriosis'],
                        ['attempted suicide'],
                        ['scleroderma'],
                        ['amyotrophy'],
                        ['flashing lights'],
                        ['collagen disease'],
                        ['heavy menstrual period'],
                        ['exophthalmos'],
                        ['colon neoplasm'],
                        ['corneal disorder'],
                        ['leukaemia'],
                        ['hepatitis c'],
                        ['dermatomyositis'],
                        ['fascitis plantar'],
                        ['als'],
                        ['carotid artery stenosis'],
                        ['bronchiectasis'],
                        ['mitral valve prolapse'],
                        ['post traumatic stress disorder'],
                        ['disorder peripheral vascular'],
                        ['cluster headache'],
                        ['postherpetic neuralgia'],
                        ['glioblastoma multiforme'],
                        ['esophageal spasm'],
                        ['paranoia'],
                        ['conversion disorder'],
                        ['excessive sleepiness'],
                        ['distended bladder'],
                        ['diabetes insipidus'],
                        ['hypoglycaemia neonatal'],
                        ['arthritis bacterial'],
                        ['hesitancy'],
                        ['hepatorenal syndrome'],
                        ['alcohol consumption'],
                        ['phlebitis superficial'],
                        ['aneurysm'],
                        ['pneumonia staphylococcal'],
                        ['scotoma'],
                        ['coronary artery bypass graft'],
                        ['vestibular disorder'],
                        ['elevated prostate specific antigen'],
                        ['disorder retinal'],
                        ['phimosis'],
                        ['neurogenic bladder'],
                        ['diabetic nephropathy'],
                        ['irritation skin'],
                        ['atrial septal defect'],
                        ['dyspareunia'],
                        ['interstitial nephritis'],
                        ['trigeminal neuralgia'],
                        ['muscle strain'],
                        ['kidney transplant'],
                        ['benign prostatic hyperplasia'],
                        ['chest wall pain'],
                        ['intervertebral disc herniation'],
                        ['transfusion reaction'],
                        ['hyperkeratosis'],
                        ['contracture'],
                        ['xerosis'],
                        ['hyperphosphatemia'],
                        ['gynaecomastia'],
                        ['thrombophlebitis'],
                        ['breast pain'],
                        ['rhagades'],
                        ['diabetic neuropathy'],
                        ['intestinal functional disorder'],
                        ['laceration'],
                        ['cerebral thrombosis'],
                        ['venous insufficiency'],
                        ['sunburn'],
                        ['synovitis'],
                        ['amyloidosis'],
                        ['monoclonal gammopathy'],
                        ['deafness'],
                        ['tardive dyskinesia'],
                        ['sick sinus syndrome'],
                        ['erysipelas'],
                        ['pancreatitis relapsing'],
                        ['lymphedema'],
                        ['bone fracture'],
                        ['diabetic retinopathy'],
                        ['tracheobronchitis'],
                        ['serum sickness'],
                        ['metabolic alkalosis'],
                        ['onychomycosis'],
                        ['lymphocytosis'],
                        ['ingrowing nail'],
                        ['lichen planus'],
                        ['carpal tunnel'],
                        ['easy bruisability'],
                        ['otitis media'],
                        ['keratitis'],
                        ['aphonia'],
                        ['tracheostomy'],
                        ['corneal ulcer'],
                        ['corneal abrasion'],
                        ['soft tissue injuries'],
                        ['glomerulonephritis'],
                        ['dermatitis seborrheic'],
                        ['major depression'],
                        ['appendectomy'],
                        ['psychosexual disorder'],
                        ['post nasal drip'],
                        ['dysphemia'],
                        ['uterine polyp'],
                        ['polymyalgia rheumatica'],
                        ['breast cyst'],
                        ['tenosynovitis'],
                        ['hirsuitism'],
                        ['brain neoplasm'],
                        ['breast tenderness'],
                        ['bipolar disorder'],
                        ['sleep walking'],
                        ['nephrogenic diabetes insipidus'],
                        ['scoliosis'],
                        ['tendon injury'],
                        ['dyshidrosis'],
                        ['abnormal cervical smear'],
                        ['adjustment disorder'],
                        ['tension headache'],
                        ['seborrhoeic keratosis'],
                        ['stress incontinence'],
                        ['temporal arteritis'],
                        ['abuse'],
                        ['drug addiction'],
                        ['diaphragmatic hernia'],
                        ['radiculopathy'],
                        ['hyperalimentation'],
                        ['mumps'],
                        ['dysmenorrhea'],
                        ['umbilical hernia'],
                        ['myelopathy'],
                        ['trigger finger'],
                        ['salivary gland inflammation'],
                        ['blepharitis'],
                        ['carotid bruit'],
                        ['breast discharge'],
                        ['animal bite'],
                        ['hyperprolactinaemia'],
                        ['cervicitis'],
                        ['pelvic inflammatory disease'],
                        ['breast dysplasia'],
                        ['injury of neck'],
                        ['rectal prolapse'],
                        ['menstrual disorder'],
                        ['optic neuritis'],
                        ['cerumen impaction'],
                        ['meningitides'],
                        ['coated tongue'],
                        ['empyema'],
                        ['rectal polyp'],
                        ['burns second degree'],
                        ['schizophrenia'],
                        ['tonsillitis'],
                        ['essential hypertension'],
                        ['sacroiliitis'],
                        ['mitral valve disease nos'],
                        ['brain concussion'],
                        ['night cramps'],
                        ['bone inflammation'],
                        ['megacolon'],
                        ['hypermetropia'],
                        ['encephalitis viral'],
                        ['hepatitis a'],
                        ['epicondylitis'],
                        ['eye infection'],
                        ['periodontitis'],
                        ['cholecystitis chronic'],
                        ['femoral neck fracture'],
                        ['pneumoconiosis'],
                        ['melanocytic naevus'],
                        ['tinea pedis'],
                        ['acute psychosis'],
                        ['sarcoidosis'],
                        ['prostatitis'],
                        ['night blindness'],
                        ['ganglion'],
                        ['volvulus'],
                        ['cystitis interstitial'],
                        ['lyme disease'],
                        ['oophorectomy'],
                        ['food poisoning'],
                        ['substance abuse'],
                        ['paraplegia'],
                        ['pyuria'],
                        ['bunion'],
                        ['hypogonadism'],
                        ['cervical dysplasia'],
                        ['ejaculation premature'],
                        ['retinal artery occlusion'],
                        ['endometriosis'],
                        ['squamous cell carcinoma of skin'],
                        ['breast enlargement'],
                        ['pancreatic cancer'],
                        ['hyperacusia'],
                        ['renal mass'],
                        ['breast swelling'],
                        ['testicular swelling'],
                        ['colostomy'],
                        ['normal pressure hydrocephalus'],
                        ['neurodermatitis'],
                        ['bad breath'],
                        ['breast inflammation'],
                        ['carcinoid syndrome'],
                        ['macrocytosis'],
                        ['balanitis'],
                        ['schizoaffective disorder'],
                        ['neck mass'],
                        ['causalgia'],
                        ['hay fever'],
                        ['coeliac disease'],
                        ['nasal polyp'],
                        ['synovial cyst'],
                        ['borderline personality disorder'],
                        ['sarcoma'],
                        ['epididymitis'],
                        ['hiv disease'],
                        ['intraocular inflammation'],
                        ['infectious mononucleosis'],
                        ['congenital heart disease'],
                        ['fracture nonunion'],
                        ['galactorrhea'],
                        ['mpd'],
                        ['sclc'],
                        ['hair disease'],
                        ['sjogrens syndrome'],
                        ['mycosis fungoides'],
                        ['fasciitis'],
                        ['tooth impacted'],
                        ['toxic shock'],
                        ['asthenopia'],
                        ['gastric ulcer perforated'],
                        ['carbuncle'],
                        ['myelitis'],
                        ['histoplasmosis'],
                        ['primary biliary cirrhosis'],
                        ['autonomic neuropathy'],
                        ['coccydynia'],
                        ['coronary angioplasty'],
                        ['telangiectases'],
                        ['spondylitis'],
                        ['methaemoglobinaemia'],
                        ['haemarthrosis'],
                        ['atypical mycobacterial infection']]
         )
))

fit_params = list(ParameterGrid(
    dict(n_epochs=[100], batch_size=[256], with_early_stopping=[True])))

drug_features_extractor_params = list(ParameterGrid(
    dict(arch=['conv1d'],
         vocab_size=[len(SMILES_ALPHABET) + 2],
         embedding_size=[20],
         cnn_sizes=[
             [256] * 4
         ],
         kernel_size=[[5]],
         dilatation_rate=[1],
         pooling_len=[2],
         b_norm=[False])
))

# network_params = list(ParameterGrid(dict(
#     network_name=['bmnddi'],
#     drug_feature_extractor_params=drug_features_extractor_params,
#     fc_layers_dim=[[128]*4],
#     mode= ["concat"],
#     dropout=[0],
#     b_norm=[True],
# )))


network_params = list(ParameterGrid(dict(
    network_name=['bmnddi'],
    drug_feature_extractor_params=drug_features_extractor_params,
    fc_layers_dim=[[128] * 2],
    mode=["concat"],
    att_hidden_dim=[None],
    dropout=[0.15],
    b_norm=[True],
)))

model_params = list(ParameterGrid(dict(
    network_params=network_params,
    optimizer=['adam'],
    lr=[1e-3],
    loss=['bce'],
    metrics_names=[['macro_roc', 'macro_auprc', 'micro_roc', 'micro_auprc']],
    use_negative_sampled_loss=[False]
)))


@click.command()
@click.option('-d', '--dataset', type=str, default='twosides', help='folder to scan')
@click.option('-a', '--algo', type=str, default='bmnddi')
@click.option('-o', '--outfile', type=str, default='configs.json')
def generate_config_file(dataset, algo, outfile):
    # todo: use argument of the function

    expt_config = dict(
        model_params=model_params,
        dataset_params=dataset_params,
        fit_params=fit_params
    )

    with open(outfile, 'w') as f:
        json.dump(expt_config, f, indent=2)


if __name__ == '__main__':
    generate_config_file()
